#### ABB EV-1 1Phase kWh Meter ####
## to add the ABB Modbus kWh meter please read the README ##

modbus_controller:
  - id: ABB2
    ## ABB EV1 meter slaveadress 2
    address: "${abb2_device_address}"
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity frome even to none on the ABB EV1 meter. Baudrate to 9600
    
sensor:
  ## 1 ABB2 Total Energy (kWh)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Import energy total"
    address: 0x5000
    register_type: holding
    value_type: U_QWORD
    device_class: "energy"
    unit_of_measurement: "kWh"
    accuracy_decimals: 4
    state_class: "total_increasing"
    filters:
    - multiply: 0.0001

  ## 2.1 ABB2 Voltage (A)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Voltage"
    register_type: holding
    address: 0x5B00
    value_type: U_DWORD
    unit_of_measurement: V
    #state_class: measurement
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  ## 2.2 ABB2 Current (A)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Current L1"
    address: 0x5B0C
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: current
    unit_of_measurement: "A"
    filters:
    - multiply: 0.01

  ## 2.3 ABB2 Active Power (Watt)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Power total"
    address: 0x5B14
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 2
    device_class: power
    unit_of_measurement: "W"
    filters:
    - multiply: 0.01

  ## 2.4 ABB2 Frequency (Hz)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Frequency"
    address: 0x5B2C
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    device_class: frequency
    unit_of_measurement: "Hz"
    filters:
    - multiply: 0.01

  ## 2.5 ABB2 Power factor (-)
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Power factor total"
    address: 0x5B3A
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 3
    device_class: power_factor
    filters:
    - multiply: 0.001

  # 6 ABB2 Info Rate
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Rated Voltage"
    address: 0x040C
    register_type: holding
    value_type: U_DWORD
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: "V"
    skip_updates: 60
    filters:
    - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Rated Current"
    address: 0x040E
    register_type: holding
    value_type: U_DWORD
    entity_category: diagnostic
    device_class: current
    unit_of_measurement: "A"
    skip_updates: 60
    filters:
    - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Maximum Current"
    address: 0x0411
    register_type: holding
    value_type: U_DWORD
    entity_category: diagnostic
    device_class: current
    unit_of_measurement: "A"
    skip_updates: 60
    filters:
    - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Rated Frequency"
    address: 0x0410
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic
    device_class: frequency
    unit_of_measurement: "Hz"
    skip_updates: 60
    filters:
    - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: ABB2
    name: "ABB2 Active pulse constant"
    address: 0x0413
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic
    unit_of_measurement: "imp/kWh"
    skip_updates: 60
